name: test-env
channels:
  - conda-forge
dependencies:
- python>=3.7
- numba
- scipy
- pip
- appmode
- pip:
  - http://viiflow.com/wp-content/uploads/vf-versions/viiflow-1.3-cp37-cp37m-linux_x86_64.whl
  - http://viiflow.com/wp-content/uploads/vf-versions/viiflowtools-1.5.1-py3-none-any.whl