name: test-env
channels:
  - conda-forge
dependencies:
- python=3.6
- numba
- scipy
- pip
- appmode
- dataclasses
- pip:
  - http://viiflow.com/wp-content/uploads/vf-versions/viiflow-1.6-cp36-cp36m-linux_x86_64.whl
  - http://viiflow.com/wp-content/uploads/vf-versions/viiflowtools-1.6-py3-none-any.whl